### ISSUE TITLE
I need to be able to get more info about each meme like upvotes

### ISSUE THREAD

**Issue by khaledbnmohamed** [arifszn/reddit-image-fetcher#1]
Thanks for the great package, I'm definitely using it. but I was asking if you can extend the response to include the upvotes as it crucial in deciding which meme to send to the user

**Comment by arifszn** [comment]
Yes, that can be added. Anymore important info suggestion?

**Comment by khaledbnmohamed** [comment]
> Yes, that can be added. Anymore important info suggestion?

Yes it'd be great if there is an options array which I can decide which attributes from the original reddit response( if you are using the reddit api) 

but for now I guess the upvotes is the most important now and thanks for your fast reply

**Comment by arifszn** [comment]
Keeping the option array suggestion for future. Upvote info has been added.
