### ISSUE TITLE
Feature Request - Allow NSFW

### ISSUE THREAD

**Issue by qtdceu** [arifszn/reddit-image-fetcher#12]
I am not very familiar with the reddit API, but I am guessing that there is no way to filter NSFW just by default. I was thinking of having an `allowNsfw` option, which would be a boolean, which would filter out any NSFW results. Sort of like this:

```js
RedditImageFetcher.fetch({
   type: 'memes',
   allowNsfw: false,
   total: 25
}).then((result) => console.log(result));
```

If this is something that seems appealing I don't mind Forking the repo and doing it myself, I imagine it would only be a relatively easy change to make. :D

**Comment by arifszn** [comment]
The problem was that the NSFW flag given from Reddit was very inaccurate at the time I made this package.

However, that may change now. This option and #8 are on my todo list. Though any PR is more than welcome. Thanks.

**Comment by qtdceu** [comment]
Hey, thanks for the quick response. I'll give it a try myself now!

**Comment by arifszn** [comment]
#13.
