### ISSUE TITLE
Error on subreddit

### ISSUE THREAD

**Issue by Nollknolle** [arifszn/reddit-image-fetcher#18]
```js
const RedditImageFetcher = require("reddit-image-fetcher");

// fetch 1 meme
RedditImageFetcher.fetch({
  subreddit: ["videos"], type: 'custom', total: 1 
}).then((result) => {
  console.log(result);
});
```

when i use this the i got an limit error.

![grafik](https://user-images.githubusercontent.com/62543404/167586470-073708da-5976-4be7-a5a7-7744b98f302b.png)

**Comment by arifszn** [comment]
I will look at it.

**Comment by arifszn** [comment]
There is no image available on the mentioned subreddit https://www.reddit.com/r/videos. As the package name suggests, it only supports gifs and images.

**Comment by Nollknolle** [comment]
Is there any way you can give an output? If I use try catch my bot crashed anyway.
